version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 863936362823.dkr.ecr.us-west-2.amazonaws.com
      - REPOSITORY_URI=863936362823.dkr.ecr.us-west-2.amazonaws.com/andychuang-php-ci
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t andychuang-php-ci .
      - docker tag andychuang-php-ci:latest 863936362823.dkr.ecr.us-west-2.amazonaws.com/andychuang-php-ci:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 863936362823.dkr.ecr.us-west-2.amazonaws.com/andychuang-php-ci:latest
      - echo Writing image definitions file...
      - printf '[{"name":"andychuang","imageUri":"%s"}]' 863936362823.dkr.ecr.us-west-2.amazonaws.com/andychuang-php-ci:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json